---

- name: docker-ce repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: no
  tags: docker

- name: install docker-ce-18.06.1.ce from docker-ce
  yum: name=docker-ce-18.06.1.ce enablerepo=docker-ce-stable state=present
  tags: docker

- name: docker running and enabled
  service: name=docker state=started enabled=yes
  tags: docker

...
