---

galaxy_info:
  author: Victoria Tepliuk
  description: Slightly modified version of https://github.com/mblomdahl/jenkins-up/tree/master/roles/docker
  company: vtepliuk Consulting

  license: Apache-2.0

  min_ansible_version: 2.5

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - docker

dependencies: []

...
